# Generated by Django 2.1.5 on 2019-02-24 20:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('learning', '0001_initial'), ('learning', '0002_auto_20190208_0218'), ('learning', '0003_auto_20190208_0502'), ('learning', '0004_auto_20190208_0547'), ('learning', '0005_auto_20190208_0615'), ('learning', '0006_auto_20190208_0618'), ('learning', '0007_lesson_original_host'), ('learning', '0008_video_duration'), ('learning', '0009_auto_20190208_0659'), ('learning', '0010_auto_20190224_1835'), ('learning', '0011_auto_20190224_1837'), ('learning', '0012_course_data'), ('learning', '0013_auto_20190224_1935')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(related_name='courses', to='learning.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('index', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=250, null=True)),
                ('original_url', models.URLField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='learning.Lesson')),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='url',
            new_name='original_url',
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='recording_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='learning.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='url',
            new_name='original_url',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_host',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
