# Generated by Django 2.1.5 on 2019-02-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='url',
            new_name='original_url',
        ),
    ]
