# Generated by Django 2.1.5 on 2019-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20190208_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
