# Generated by Django 2.1.5 on 2019-02-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20190208_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
