# Generated by Django 2.1.5 on 2019-02-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190208_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='url',
            new_name='original_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='original_url',
        ),
    ]
