# Generated by Django 2.1.5 on 2019-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190208_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='original_host',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
