# Generated by Django 2.1.5 on 2019-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_lesson_original_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
