# Generated by Django 2.1.5 on 2019-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20190208_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
