# Generated by Django 2.1.5 on 2019-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_course_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='original_host',
        ),
        migrations.AddField(
            model_name='course',
            name='original_host',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
